-- This file is part of SA MoonLoader package.
-- Licensed under the MIT License.
-- Copyright (c) 2016, BlastHack Team <blast.hk>


local keys = {
	VK_LBUTTON = 0x01,
	VK_RBUTTON = 0x02,
	VK_CANCEL = 0x03,
	VK_MBUTTON = 0x04,
	VK_XBUTTON1 = 0x05,
	VK_XBUTTON2 = 0x06,
	VK_BACK = 0x08,
	VK_TAB = 0x09,
	VK_CLEAR = 0x0C,
	VK_RETURN = 0x0D,
	VK_SHIFT = 0x10,
	VK_CONTROL = 0x11,
	VK_MENU = 0x12,
	VK_PAUSE = 0x13,
	VK_CAPITAL = 0x14,
	VK_KANA = 0x15,
	VK_JUNJA = 0x17,
	VK_FINAL = 0x18,
	VK_KANJI = 0x19,
	VK_ESCAPE = 0x1B,
	VK_CONVERT = 0x1C,
	VK_NONCONVERT = 0x1D,
	VK_ACCEPT = 0x1E,
	VK_MODECHANGE = 0x1F,
	VK_SPACE = 0x20,
	VK_PRIOR = 0x21,
	VK_NEXT = 0x22,
	VK_END = 0x23,
	VK_HOME = 0x24,
	VK_LEFT = 0x25,
	VK_UP = 0x26,
	VK_RIGHT = 0x27,
	VK_DOWN = 0x28,
	VK_SELECT = 0x29,
	VK_PRINT = 0x2A,
	VK_EXECUTE = 0x2B,
	VK_SNAPSHOT = 0x2C,
	VK_INSERT = 0x2D,
	VK_DELETE = 0x2E,
	VK_HELP = 0x2F,
	VK_0 = 0x30,
	VK_1 = 0x31,
	VK_2 = 0x32,
	VK_3 = 0x33,
	VK_4 = 0x34,
	VK_5 = 0x35,
	VK_6 = 0x36,
	VK_7 = 0x37,
	VK_8 = 0x38,
	VK_9 = 0x39,
	VK_A = 0x41,
	VK_B = 0x42,
	VK_C = 0x43,
	VK_D = 0x44,
	VK_E = 0x45,
	VK_F = 0x46,
	VK_G = 0x47,
	VK_H = 0x48,
	VK_I = 0x49,
	VK_J = 0x4A,
	VK_K = 0x4B,
	VK_L = 0x4C,
	VK_M = 0x4D,
	VK_N = 0x4E,
	VK_O = 0x4F,
	VK_P = 0x50,
	VK_Q = 0x51,
	VK_R = 0x52,
	VK_S = 0x53,
	VK_T = 0x54,
	VK_U = 0x55,
	VK_V = 0x56,
	VK_W = 0x57,
	VK_X = 0x58,
	VK_Y = 0x59,
	VK_Z = 0x5A,
	VK_LWIN = 0x5B,
	VK_RWIN = 0x5C,
	VK_APPS = 0x5D,
	VK_SLEEP = 0x5F,
	VK_NUMPAD0 = 0x60,
	VK_NUMPAD1 = 0x61,
	VK_NUMPAD2 = 0x62,
	VK_NUMPAD3 = 0x63,
	VK_NUMPAD4 = 0x64,
	VK_NUMPAD5 = 0x65,
	VK_NUMPAD6 = 0x66,
	VK_NUMPAD7 = 0x67,
	VK_NUMPAD8 = 0x68,
	VK_NUMPAD9 = 0x69,
	VK_MULTIPLY = 0x6A,
	VK_ADD = 0x6B,
	VK_SEPARATOR = 0x6C,
	VK_SUBTRACT = 0x6D,
	VK_DECIMAL = 0x6E,
	VK_DIVIDE = 0x6F,
	VK_F1 = 0x70,
	VK_F2 = 0x71,
	VK_F3 = 0x72,
	VK_F4 = 0x73,
	VK_F5 = 0x74,
	VK_F6 = 0x75,
	VK_F7 = 0x76,
	VK_F8 = 0x77,
	VK_F9 = 0x78,
	VK_F10 = 0x79,
	VK_F11 = 0x7A,
	VK_F12 = 0x7B,
	VK_F13 = 0x7C,
	VK_F14 = 0x7D,
	VK_F15 = 0x7E,
	VK_F16 = 0x7F,
	VK_F17 = 0x80,
	VK_F18 = 0x81,
	VK_F19 = 0x82,
	VK_F20 = 0x83,
	VK_F21 = 0x84,
	VK_F22 = 0x85,
	VK_F23 = 0x86,
	VK_F24 = 0x87,
	VK_NUMLOCK = 0x90,
	VK_SCROLL = 0x91,
	VK_OEM_FJ_JISHO = 0x92,
	VK_OEM_FJ_MASSHOU = 0x93,
	VK_OEM_FJ_TOUROKU = 0x94,
	VK_OEM_FJ_LOYA = 0x95,
	VK_OEM_FJ_ROYA = 0x96,
	VK_LSHIFT = 0xA0,
	VK_RSHIFT = 0xA1,
	VK_LCONTROL = 0xA2,
	VK_RCONTROL = 0xA3,
	VK_LMENU = 0xA4,
	VK_RMENU = 0xA5,
	VK_BROWSER_BACK = 0xA6,
	VK_BROWSER_FORWARD = 0xA7,
	VK_BROWSER_REFRESH = 0xA8,
	VK_BROWSER_STOP = 0xA9,
	VK_BROWSER_SEARCH = 0xAA,
	VK_BROWSER_FAVORITES = 0xAB,
	VK_BROWSER_HOME = 0xAC,
	VK_VOLUME_MUTE = 0xAD,
	VK_VOLUME_DOWN = 0xAE,
	VK_VOLUME_UP = 0xAF,
	VK_MEDIA_NEXT_TRACK = 0xB0,
	VK_MEDIA_PREV_TRACK = 0xB1,
	VK_MEDIA_STOP = 0xB2,
	VK_MEDIA_PLAY_PAUSE = 0xB3,
	VK_LAUNCH_MAIL = 0xB4,
	VK_LAUNCH_MEDIA_SELECT = 0xB5,
	VK_LAUNCH_APP1 = 0xB6,
	VK_LAUNCH_APP2 = 0xB7,
	VK_OEM_1 = 0xBA,
	VK_OEM_PLUS = 0xBB,
	VK_OEM_COMMA = 0xBC,
	VK_OEM_MINUS = 0xBD,
	VK_OEM_PERIOD = 0xBE,
	VK_OEM_2 = 0xBF,
	VK_OEM_3 = 0xC0,
	VK_ABNT_C1 = 0xC1,
	VK_ABNT_C2 = 0xC2,
	VK_OEM_4 = 0xDB,
	VK_OEM_5 = 0xDC,
	VK_OEM_6 = 0xDD,
	VK_OEM_7 = 0xDE,
	VK_OEM_8 = 0xDF,
	VK_OEM_AX = 0xE1,
	VK_OEM_102 = 0xE2,
	VK_ICO_HELP = 0xE3,
	VK_PROCESSKEY = 0xE5,
	VK_ICO_CLEAR = 0xE6,
	VK_PACKET = 0xE7,
	VK_OEM_RESET = 0xE9,
	VK_OEM_JUMP = 0xEA,
	VK_OEM_PA1 = 0xEB,
	VK_OEM_PA2 = 0xEC,
	VK_OEM_PA3 = 0xED,
	VK_OEM_WSCTRL = 0xEE,
	VK_OEM_CUSEL = 0xEF,
	VK_OEM_ATTN = 0xF0,
	VK_OEM_FINISH = 0xF1,
	VK_OEM_COPY = 0xF2,
	VK_OEM_AUTO = 0xF3,
	VK_OEM_ENLW = 0xF4,
	VK_OEM_BACKTAB = 0xF5,
	VK_ATTN = 0xF6,
	VK_CRSEL = 0xF7,
	VK_EXSEL = 0xF8,
	VK_EREOF = 0xF9,
	VK_PLAY = 0xFA,
	VK_ZOOM = 0xFB,
	VK_PA1 = 0xFD,
	VK_OEM_CLEAR = 0xFE,
}

local keyNames = {
    [keys.VK_LBUTTON] = { category = "Mouse", name = "Left Button" },
    [keys.VK_RBUTTON] = { category = "Mouse", name = "Right Button" },
    [keys.VK_CANCEL] = { category = "Mouse", name = "Cancel" },
    [keys.VK_MBUTTON] = { category = "Mouse", name = "Middle Button" },
    [keys.VK_XBUTTON1] = { category = "Mouse", name = "X Button 1" },
    [keys.VK_XBUTTON2] = { category = "Mouse", name = "X Button 2" },
    [keys.VK_BACK] = { category = "Keyboard", name = "Backspace" },
    [keys.VK_TAB] = { category = "Keyboard", name = "Tab" },
    [keys.VK_CLEAR] = { category = "Keyboard", name = "Clear" },
    [keys.VK_RETURN] = { category = "Keyboard", name = "Enter" },
    [keys.VK_SHIFT] = { category = "Keyboard", name = "Shift" },
    [keys.VK_CONTROL] = { category = "Keyboard", name = "Ctrl" },
    [keys.VK_MENU] = { category = "Keyboard", name = "Alt" },
    [keys.VK_PAUSE] = { category = "Keyboard", name = "Pause" },
    [keys.VK_CAPITAL] = { category = "Keyboard", name = "Caps Lock" },
    [keys.VK_KANA] = { category = "Keyboard", name = "Kana" },
    [keys.VK_JUNJA] = { category = "Keyboard", name = "Junja" },
    [keys.VK_FINAL] = { category = "Keyboard", name = "Final" },
    [keys.VK_KANJI] = { category = "Keyboard", name = "Kanji" },
    [keys.VK_ESCAPE] = { category = "Keyboard", name = "Esc" },
    [keys.VK_CONVERT] = { category = "Keyboard", name = "Convert" },
    [keys.VK_NONCONVERT] = { category = "Keyboard", name = "Non Convert" },
    [keys.VK_ACCEPT] = { category = "Keyboard", name = "Accept" },
    [keys.VK_MODECHANGE] = { category = "Keyboard", name = "Mode Change" },
    [keys.VK_SPACE] = { category = "Keyboard", name = "Space" },
    [keys.VK_PRIOR] = { category = "Keyboard", name = "Page Up" },
    [keys.VK_NEXT] = { category = "Keyboard", name = "Page Down" },
    [keys.VK_END] = { category = "Keyboard", name = "End" },
    [keys.VK_HOME] = { category = "Keyboard", name = "Home" },
    [keys.VK_LEFT] = { category = "Keyboard", name = "Arrow Left" },
    [keys.VK_UP] = { category = "Keyboard", name = "Arrow Up" },
    [keys.VK_RIGHT] = { category = "Keyboard", name = "Arrow Right" },
    [keys.VK_DOWN] = { category = "Keyboard", name = "Arrow Down" },
    [keys.VK_SELECT] = { category = "Keyboard", name = "Select" },
    [keys.VK_PRINT] = { category = "Keyboard", name = "Print" },
    [keys.VK_EXECUTE] = { category = "Keyboard", name = "Execute" },
    [keys.VK_SNAPSHOT] = { category = "Keyboard", name = "Print Screen" },
    [keys.VK_INSERT] = { category = "Keyboard", name = "Insert" },
    [keys.VK_DELETE] = { category = "Keyboard", name = "Delete" },
    [keys.VK_HELP] = { category = "Keyboard", name = "Help" },
    [keys.VK_0] = { category = "Nummer", name = "0" },
    [keys.VK_1] = { category = "Nummer", name = "1" },
    [keys.VK_2] = { category = "Nummer", name = "2" },
    [keys.VK_3] = { category = "Nummer", name = "3" },
    [keys.VK_4] = { category = "Nummer", name = "4" },
    [keys.VK_5] = { category = "Nummer", name = "5" },
    [keys.VK_6] = { category = "Nummer", name = "6" },
    [keys.VK_7] = { category = "Nummer", name = "7" },
    [keys.VK_8] = { category = "Nummer", name = "8" },
    [keys.VK_9] = { category = "Nummer", name = "9" },
    [keys.VK_A] = { category = "Letter", name = "A" },
    [keys.VK_B] = { category = "Letter", name = "B" },
    [keys.VK_C] = { category = "Letter", name = "C" },
    [keys.VK_D] = { category = "Letter", name = "D" },
    [keys.VK_E] = { category = "Letter", name = "E" },
    [keys.VK_F] = { category = "Letter", name = "F" },
    [keys.VK_G] = { category = "Letter", name = "G" },
    [keys.VK_H] = { category = "Letter", name = "H" },
    [keys.VK_I] = { category = "Letter", name = "I" },
    [keys.VK_J] = { category = "Letter", name = "J" },
    [keys.VK_K] = { category = "Letter", name = "K" },
    [keys.VK_L] = { category = "Letter", name = "L" },
    [keys.VK_M] = { category = "Letter", name = "M" },
    [keys.VK_N] = { category = "Letter", name = "N" },
    [keys.VK_O] = { category = "Letter", name = "O" },
    [keys.VK_P] = { category = "Letter", name = "P" },
    [keys.VK_Q] = { category = "Letter", name = "Q" },
    [keys.VK_R] = { category = "Letter", name = "R" },
    [keys.VK_S] = { category = "Letter", name = "S" },
    [keys.VK_T] = { category = "Letter", name = "T" },
    [keys.VK_U] = { category = "Letter", name = "U" },
    [keys.VK_V] = { category = "Letter", name = "V" },
    [keys.VK_W] = { category = "Letter", name = "W" },
    [keys.VK_X] = { category = "Letter", name = "X" },
    [keys.VK_Y] = { category = "Letter", name = "Y" },
    [keys.VK_Z] = { category = "Letter", name = "Z" },
    [keys.VK_LWIN] = { category = "Keyboard", name = "Left Windows" },
    [keys.VK_RWIN] = { category = "Keyboard", name = "Right Windows" },
    [keys.VK_APPS] = { category = "Keyboard", name = "Apps" },
    [keys.VK_SLEEP] = { category = "Keyboard", name = "Sleep" },
    [keys.VK_NUMPAD0] = { category = "Numpad", name = "Numpad 0" },
    [keys.VK_NUMPAD1] = { category = "Numpad", name = "Numpad 1" },
    [keys.VK_NUMPAD2] = { category = "Numpad", name = "Numpad 2" },
    [keys.VK_NUMPAD3] = { category = "Numpad", name = "Numpad 3" },
    [keys.VK_NUMPAD4] = { category = "Numpad", name = "Numpad 4" },
    [keys.VK_NUMPAD5] = { category = "Numpad", name = "Numpad 5" },
    [keys.VK_NUMPAD6] = { category = "Numpad", name = "Numpad 6" },
    [keys.VK_NUMPAD7] = { category = "Numpad", name = "Numpad 7" },
    [keys.VK_NUMPAD8] = { category = "Numpad", name = "Numpad 8" },
    [keys.VK_NUMPAD9] = { category = "Numpad", name = "Numpad 9" },
    [keys.VK_MULTIPLY] = { category = "Keyboard", name = "Multiply" },
    [keys.VK_ADD] = { category = "Keyboard", name = "Add" },
    [keys.VK_SEPARATOR] = { category = "Keyboard", name = "Separator" },
    [keys.VK_SUBTRACT] = { category = "Keyboard", name = "Subtract" },
    [keys.VK_DECIMAL] = { category = "Keyboard", name = "Decimal" },
    [keys.VK_DIVIDE] = { category = "Keyboard", name = "Divide" },
    [keys.VK_F1] = { category = "Keyboard", name = "F1" },
    [keys.VK_F2] = { category = "Keyboard", name = "F2" },
    [keys.VK_F3] = { category = "Keyboard", name = "F3" },
    [keys.VK_F4] = { category = "Keyboard", name = "F4" },
    [keys.VK_F5] = { category = "Keyboard", name = "F5" },
    [keys.VK_F6] = { category = "Keyboard", name = "F6" },
    [keys.VK_F7] = { category = "Keyboard", name = "F7" },
    [keys.VK_F8] = { category = "Keyboard", name = "F8" },
    [keys.VK_F9] = { category = "Keyboard", name = "F9" },
    [keys.VK_F10] = { category = "Keyboard", name = "F10" },
    [keys.VK_F11] = { category = "Keyboard", name = "F11" },
    [keys.VK_F12] = { category = "Keyboard", name = "F12" },
    [keys.VK_F13] = { category = "Keyboard", name = "F13" },
    [keys.VK_F14] = { category = "Keyboard", name = "F14" },
    [keys.VK_F15] = { category = "Keyboard", name = "F15" },
    [keys.VK_F16] = { category = "Keyboard", name = "F16" },
    [keys.VK_F17] = { category = "Keyboard", name = "F17" },
    [keys.VK_F18] = { category = "Keyboard", name = "F18" },
    [keys.VK_F19] = { category = "Keyboard", name = "F19" },
    [keys.VK_F20] = { category = "Keyboard", name = "F20" },
    [keys.VK_F21] = { category = "Keyboard", name = "F21" },
    [keys.VK_F22] = { category = "Keyboard", name = "F22" },
    [keys.VK_F23] = { category = "Keyboard", name = "F23" },
    [keys.VK_F24] = { category = "Keyboard", name = "F24" },
    [keys.VK_NUMLOCK] = { category = "Keyboard", name = "Num Lock" },
    [keys.VK_SCROLL] = { category = "Keyboard", name = "Scroll Lock" },
    [keys.VK_OEM_FJ_JISHO] = { category = "Keyboard", name = "OEM FJ Jisho" },
    [keys.VK_OEM_FJ_MASSHOU] = { category = "Keyboard", name = "OEM FJ Masshou" },
    [keys.VK_OEM_FJ_TOUROKU] = { category = "Keyboard", name = "OEM FJ Touroku" },
    [keys.VK_OEM_FJ_LOYA] = { category = "Keyboard", name = "OEM FJ Loya" },
    [keys.VK_OEM_FJ_ROYA] = { category = "Keyboard", name = "OEM FJ Roya" },
    [keys.VK_LSHIFT] = { category = "KeyAccion", name = "Left Shift" },
    [keys.VK_RSHIFT] = { category = "KeyAccion", name = "Right Shift" },
    [keys.VK_LCONTROL] = { category = "KeyAccion", name = "Left Ctrl" },
    [keys.VK_RCONTROL] = { category = "KeyAccion", name = "Right Ctrl" },
    [keys.VK_LMENU] = { category = "KeyAccion", name = "Left Alt" },
    [keys.VK_RMENU] = { category = "KeyAccion", name = "Right Alt" },
    [keys.VK_BROWSER_BACK] = { category = "Keyboard", name = "Browser Back" },
    [keys.VK_BROWSER_FORWARD] = { category = "Keyboard", name = "Browser Forward" },
    [keys.VK_BROWSER_REFRESH] = { category = "Keyboard", name = "Browser Refresh" },
    [keys.VK_BROWSER_STOP] = { category = "Keyboard", name = "Browser Stop" },
    [keys.VK_BROWSER_SEARCH] = { category = "Keyboard", name = "Browser Search" },
    [keys.VK_BROWSER_FAVORITES] = { category = "Keyboard", name = "Browser Favorites" },
    [keys.VK_BROWSER_HOME] = { category = "Keyboard", name = "Browser Home" },
    [keys.VK_VOLUME_MUTE] = { category = "Keyboard", name = "Volume Mute" },
    [keys.VK_VOLUME_DOWN] = { category = "Keyboard", name = "Volume Down" },
    [keys.VK_VOLUME_UP] = { category = "Keyboard", name = "Volume Up" },
    [keys.VK_MEDIA_NEXT_TRACK] = { category = "Keyboard", name = "Next Track" },
    [keys.VK_MEDIA_PREV_TRACK] = { category = "Keyboard", name = "Previous Track" },
    [keys.VK_MEDIA_STOP] = { category = "Keyboard", name = "Media Stop" },
    [keys.VK_MEDIA_PLAY_PAUSE] = { category = "Keyboard", name = "Play/Pause" },
    [keys.VK_LAUNCH_MAIL] = { category = "Keyboard", name = "Launch Mail" },
    [keys.VK_LAUNCH_MEDIA_SELECT] = { category = "Keyboard", name = "Launch Media Select" },
    [keys.VK_LAUNCH_APP1] = { category = "Keyboard", name = "Launch App1" },
    [keys.VK_LAUNCH_APP2] = { category = "Keyboard", name = "Launch App2" },
    [keys.VK_OEM_1] = { category = "Keyboard", name = "OEM 1" },
    [keys.VK_OEM_PLUS] = { category = "Keyboard", name = "OEM Plus" },
    [keys.VK_OEM_COMMA] = { category = "Keyboard", name = "OEM Comma" },
    [keys.VK_OEM_MINUS] = { category = "Keyboard", name = "OEM Minus" },
    [keys.VK_OEM_PERIOD] = { category = "Keyboard", name = "OEM Period" },
    [keys.VK_OEM_2] = { category = "Keyboard", name = "OEM 2" },
    [keys.VK_OEM_3] = { category = "Keyboard", name = "OEM 3" },
    [keys.VK_ABNT_C1] = { category = "Keyboard", name = "ABNT C1" },
    [keys.VK_ABNT_C2] = { category = "Keyboard", name = "ABNT C2" },
    [keys.VK_OEM_4] = { category = "Keyboard", name = "OEM 4" },
    [keys.VK_OEM_5] = { category = "Keyboard", name = "OEM 5" },
    [keys.VK_OEM_6] = { category = "Keyboard", name = "OEM 6" },
    [keys.VK_OEM_7] = { category = "Keyboard", name = "OEM 7" },
    [keys.VK_OEM_8] = { category = "Keyboard", name = "OEM 8" },
    [keys.VK_OEM_AX] = { category = "Keyboard", name = "OEM AX" },
    [keys.VK_OEM_102] = { category = "Keyboard", name = "OEM 102" },
    [keys.VK_ICO_HELP] = { category = "Keyboard", name = "ICO Help" },
    [keys.VK_PROCESSKEY] = { category = "Keyboard", name = "Process Key" },
    [keys.VK_ICO_CLEAR] = { category = "Keyboard", name = "ICO Clear" },
    [keys.VK_PACKET] = { category = "Keyboard", name = "Packet" },
    [keys.VK_OEM_RESET] = { category = "Keyboard", name = "OEM Reset" },
    [keys.VK_OEM_JUMP] = { category = "Keyboard", name = "OEM Jump" },
    [keys.VK_OEM_PA1] = { category = "Keyboard", name = "OEM PA1" },
    [keys.VK_OEM_PA2] = { category = "Keyboard", name = "OEM PA2" },
    [keys.VK_OEM_PA3] = { category = "Keyboard", name = "OEM PA3" },
    [keys.VK_OEM_WSCTRL] = { category = "Keyboard", name = "OEM WSCTRL" },
    [keys.VK_OEM_CUSEL] = { category = "Keyboard", name = "OEM CUSEL" },
    [keys.VK_OEM_ATTN] = { category = "Keyboard", name = "OEM Attn" },
    [keys.VK_OEM_FINISH] = { category = "Keyboard", name = "OEM Finish" },
    [keys.VK_OEM_COPY] = { category = "Keyboard", name = "OEM Copy" },
    [keys.VK_OEM_AUTO] = { category = "Keyboard", name = "OEM Auto" },
    [keys.VK_OEM_ENLW] = { category = "Keyboard", name = "OEM Enlw" },
    [keys.VK_OEM_BACKTAB] = { category = "Keyboard", name = "OEM Backtab" },
    [keys.VK_ATTN] = { category = "Keyboard", name = "Attn" },
    [keys.VK_CRSEL] = { category = "Keyboard", name = "Cr Sel" },
    [keys.VK_EXSEL] = { category = "Keyboard", name = "Ex Sel" },
    [keys.VK_EREOF] = { category = "Keyboard", name = "Er Eof" },
    [keys.VK_PLAY] = { category = "Keyboard", name = "Play" },
    [keys.VK_ZOOM] = { category = "Keyboard", name = "Zoom" },
    [keys.VK_PA1] = { category = "Keyboard", name = "PA1" },
    [keys.VK_OEM_CLEAR] = { category = "Keyboard", name = "OEM Clear" },
}


keys.key_names = keyNames

function keys.id_to_name(vkey)
	local name = keyNames[vkey]
	if type(name) == 'table' then
		return name[1]
	end
	return name
end

function keys.name_to_id(keyname, case_sensitive)
    if not case_sensitive then
        keyname = string.upper(keyname)
    end
    for id, v in pairs(keys) do
        if type(v) == 'table' then
            for _, name in ipairs(v) do
                local compare_name = (case_sensitive) and name or string.upper(name)
                if compare_name == keyname then
                    return id
                end
            end
        else
            local compare_name = (case_sensitive) and v or string.upper(v)
            if compare_name == keyname then
                return id
            end
        end
    end
end

function keys.key_is_mouse(vkey)
	local key = keyNames[vkey]
    if(key ~= nil) then return (key.category == 'Mouse')
    else return nil end
end

function keys.get_key_pressed()
    while true do
        wait(0)
        for _, v in pairs(keys) do
            if isKeyJustPressed(v) and not keys.key_is_mouse(v) then
                return keyNames[v] 
            end
        end
    end
end

return keys